//
// Created by Даник 💪 on 27.10.2023.
//

#ifndef RUNTIME_SRC_CONSTRUCTIONS_INCLUDE_CONSTRUCTIONS_CONSTRUCTIONSTREAMEXTRACTORSTATE_H_
#define RUNTIME_SRC_CONSTRUCTIONS_INCLUDE_CONSTRUCTIONS_CONSTRUCTIONSTREAMEXTRACTORSTATE_H_

#include "boost/circular_buffer.hpp"

struct ConstructionStreamExtractorState {
  boost::circular_buffer<char> buffer_;
};

#endif //RUNTIME_SRC_CONSTRUCTIONS_INCLUDE_CONSTRUCTIONS_CONSTRUCTIONSTREAMEXTRACTORSTATE_H_
