//
// Created by Даник 💪 on 27.10.2023.
//

#ifndef RUNTIME_SRC_HANDLERS_INCLUDE_HANDLERS_TRYADDCONSTRUCTIONRESULT_H_
#define RUNTIME_SRC_HANDLERS_INCLUDE_HANDLERS_TRYADDCONSTRUCTIONRESULT_H_

struct TryAddConstructionResult {
  bool save_current_character;
};

#endif //RUNTIME_SRC_HANDLERS_INCLUDE_HANDLERS_TRYADDCONSTRUCTIONRESULT_H_
