//
// Created by Даник 💪 on 10.10.2023.
//

#ifndef RUNTIME_SRC_CONSTRUCTIONHANDLERS_INCLUDE_CONSTRUCTIONHANDLERS_ICONSTRUCTIONHANDLERDELETER_H_
#define RUNTIME_SRC_CONSTRUCTIONHANDLERS_INCLUDE_CONSTRUCTIONHANDLERS_ICONSTRUCTIONHANDLERDELETER_H_

#include "IConstructionHandler.h"

struct IConstructionHandlerDeleter {
  void operator()(IConstructionHandler* p) const { delete p; }
};

#endif //RUNTIME_SRC_CONSTRUCTIONHANDLERS_INCLUDE_CONSTRUCTIONHANDLERS_ICONSTRUCTIONHANDLERDELETER_H_
