//
// Created by Даник 💪 on 11.11.2023.
//

#ifndef RUNTIME_SRC_SCOPEANALYZERSTATE_INCLUDE_SCOPEANALYZERSTATE_INDENTATIONANALYZERSTATE_H_
#define RUNTIME_SRC_SCOPEANALYZERSTATE_INCLUDE_SCOPEANALYZERSTATE_INDENTATIONANALYZERSTATE_H_

#include "Constructions/Construction.h"

#include <memory>

struct IndentationAnalyzerState {
};

#endif //RUNTIME_SRC_SCOPEANALYZERSTATE_INCLUDE_SCOPEANALYZERSTATE_INDENTATIONANALYZERSTATE_H_
